import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import Form from "react-bootstrap/Form";
import React, {useState} from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Login() {
  const[username, setUsername] = useState('');
  const[pass, setPass] = useState('');

  const handleSubmit = (e) => {
    e.preventDefault();
    console.log(username);
    console.log(pass);
  }
  return (
    <>
      <div className = "auth-form-container">
      <form className = "login-form" onSubmit={handleSubmit}>
        <label className="loginbuff">LOG in to BuffsU</label> <br/>
        <label htmlFor="username" >IdentiKey Username (example: ralph1234) : </label>
        {/* <input value={username} type = "username" placeholder="ralp1234" id="username" name = "username" /> */}
        <input value={username} onChange={(e) => setUsername(e.target.value)} type = "username" />
        <label htmlFor="password">Password : </label>
        {/* <input value={pass} type = "password" placeholder="******" id="password" name = "password" /> */}
        <input value={pass} onChange={(e) => setPass(e.target.value)} type = "password"  /> <br/>
        <button type = "submit">Log In</button>
      </form>
      {/* <button className="link">Don't have an account? Register here.</button> */}
      </div>
      {/* <button></button> */}

      {/* <form>
        <label htmlFor="username" >IdentiKey Username : </label>
        <input value=(username) onChange((e) => setUsername(e.target.value)) type = "username" placeholder="ralp1234" id="username" name = "username" />
        <label htmlFor="password">Password : </label>
        <input value=(pass) onChange((e) => setPass(e.target.value)) type = "password" placeholder="******" id="password" name = "password" />
        <button type = "submit">Log In</button>
      </form> */}
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      {/* <main className={styles.main}> */}
        {/* <div>Hello, Sanjana Login Page</div>  */}
        {/* <Form.Group controlId="login">

            <Form.Label>Email</Form.Label>

            <Form.Control type="email" value={"Ralphie"}/>

          <Form.Label>Password</Form.Label>

          <Form.Control type="password" value={"123"}/>

          {/* <Button block size="lg" type="submit" disabled={!validateForm()}> Login </Button>

        </Form.Group> */}
        {/* <Form>
            <label>Email</label>
            <input type="email"></input> 
            <label>Password</label>
            <input type="password"></input>
        </Form> */}
      {/* </main> */}
    </>
  );
}